
services:
# MARIADB
  mariadb:
    # Custom image name
    image: ${USER}/mariadb:latest
    # Container name
    container_name: mariadb
    build:
      # Where is the Dockerfile
      context: ./requirements/mariadb
      # Arguments for the Dockerfile (used in the build process)
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
        WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    # Networks to which the service is connected
    networks:
      - net
    # Volumes to which the service is connected
    volumes:
      - mariadb_volume:/var/lib/mysql
    # Healthcheck to ensure the service is correctly running
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 5
      interval: 2s
      timeout: 5s
    # Restart policy
    restart: always
#--------------------------------------
# WORDPRESS
  wordpress:
    image: ${USER}/wordpress:latest
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - net
    volumes:
      - wordpress_volume:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_SITE_URL: ${WORDPRESS_SITE_URL}
      WORDPRESS_SITE_TITLE: ${WORDPRESS_SITE_TITLE}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_SECONDARY_USER: ${WORDPRESS_SECONDARY_USER}
      WORDPRESS_SECONDARY_USER_EMAIL: ${WORDPRESS_SECONDARY_USER_EMAIL}
      WORDPRESS_SECONDARY_USER_PASSWORD: ${WORDPRESS_SECONDARY_USER_PASSWORD}
    restart: always
#--------------------------------------
# NGINX
  nginx:
    image: ${USER}/nginx:latest
    container_name: nginx
    build:
      context: ./requirements/nginx
      args:
        - LOGIN=${USER}
    depends_on:
        - wordpress
    networks:
      - net
    volumes:
        - wordpress_volume:/var/www/html
    ports:
        - 443:443
    restart: always
#------------------------------------------------------------------------------
# NETWORKS
networks:
  net:
    driver: bridge
#------------------------------------------------------------------------------
# VOLUMES
volumes:
  mariadb_volume:
    name: ${MARIADB_VOLUME_NAME}
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_VOLUME_PATH}
  wordpress_volume:
    name: ${WORDPRESS_VOLUME_NAME}
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_VOLUME_PATH}
#------------------------------------------------------------------------------